// This is an autogenerated file - DO NOT EDIT DIRECTLY
// This file was generated on Mon May 10 2021 14:19:52 GMT-0700 (Pacific Daylight Time) via the forge in willcarh.art v2.1.0
// Learn more: https://github.com/wcarhart/willcarh.art
// THIS IS A DEVELOPMENT BUILD, PROCEED WITH CAUTION

// handle clicks and resizing
$(document).ready(async () => {
	$('.blog-border').click(async function() {
		let blog = this.id.replace(/^blog-card-/, '')
		blog = blog.replace(/^latest-/, '')
		window.location.href = `blog/${blog}.html`
	})

	await resizeBlogCards()
	// TODO: verify this actually works
	$(window).resize(async () => {
		await resizeBlogCards()
	})
})

// resize blog cards based on screen size
const resizeBlogCards = async () => {

	// wait for page to settle
	await new Promise(r => setTimeout(r, 500));

	// re-size cards in rows one at a time
	let index = -1
	do {
		// start with row 0
		index += 1

		// calculate dynamic row heights
		let maxRowHeight = 0
		let rowHeights = []
		for (let el of $(`.blog-row-${index}`)) {
			let height = $(el).height()
			if (height > maxRowHeight) {
				maxRowHeight = height
			}
			rowHeights.push(height)
		}

		// update row heights
		for (let columnIndex = 0; columnIndex < 2; columnIndex++) {
			let finalIndex = index*2 + columnIndex
			let height = rowHeights[columnIndex]
			if (height < maxRowHeight) {
				// we add 1rem to the additional height because that's how much margin there was to begin with
				$(`#blog-spacer-${finalIndex}`).css('margin-bottom', 16 + maxRowHeight - height)
			}
		}

	} while ($(`.blog-row-${index+1}`).length !== 0)
}