// This is an autogenerated file - DO NOT EDIT DIRECTLY
// This file was generated on Mon Mar 08 2021 04:17:33 GMT-0800 (Pacific Standard Time) via the forge in willcarh.art v2.0.0
// Learn more: https://github.com/wcarhart/willcarh.art
// THIS IS A DEVELOPMENT BUILD, PROCEED WITH CAUTION!

// handle clicks on blog nav items
$(document).ready(async () => {
	$('#blog-navigation-back').click(async function() {
		window.location.href = window.location.href.replace(/blog.*$/, 'blog_index.html')
	})

	$('#blog-navigation-next').click(async function() {
		let nextPost = $('#next-blog-link').text()
		window.location.href = window.location.href.replace(/blog.*$/, `blog/${nextPost}.html`)
	})
})
