// This is an autogenerated file - DO NOT EDIT DIRECTLY
// This file was generated on Sat Nov 28 2020 02:49:49 GMT-0700 (Mountain Standard Time) via the forge in willcarh.art v2.0.0
// Learn more: https://github.com/wcarhart/willcarh.art