// This is an autogenerated file - DO NOT EDIT DIRECTLY
// This file was generated on Thu Nov 26 2020 12:13:58 GMT-0700 (Mountain Standard Time) via the forge in willcarh.art v2.0.0
// Learn more: https://github.com/wcarhart/willcarh.art