// This is an autogenerated file - DO NOT EDIT DIRECTLY
// This file was generated on Thu Nov 12 2020 10:54:25 GMT-0800 (Pacific Standard Time) via the forge in willcarh.art v2.0.0
// Learn more: https://github.com/wcarhart/willcarh.art

// handle hover and click for project cards
$(document).ready(async () => {
	// handle animations for hover
	$('.project-border').hover(async function() {
		const id = `#title-${this.id.replace('proj-', '')}`
		$(id).css('background-size', '100% 0.125rem')
		$(this).css('cursor', 'pointer')
	}, async function() {
		const id = `#title-${this.id.replace('proj-', '')}`
		$(id).css('background-size', '0% 0.125rem')
	})

	// TODO
	// handle click to specific project
	$('.project-border').click(async function() {
		console.log(this.id)
	})
})
