// This is an autogenerated file - DO NOT EDIT DIRECTLY
// This file was generated on Sun Mar 07 2021 11:46:08 GMT-0800 (Pacific Standard Time) via the forge in willcarh.art v2.0.0
// Learn more: https://github.com/wcarhart/willcarh.art
// THIS IS A DEVELOPMENT BUILD, PROCEED WITH CAUTION!

// dynamically update footer year
const year = new Date().getFullYear();
$(document).ready(async () => {
	$('#year').text(year)
})
