name: eslint
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: yarn install
    - name: eslint
      run: yarn run eslint generator/*